### ISSUE TITLE
Failed to install slick carousel

### ISSUE THREAD

**Issue by mariohernandez** [mediacurrent/theme_generator_8#59]
When creating a new theme and selecting the slick carousel as one of the components, the following error comes up:
`Failed to install slick carousel`.
<img width="1251" alt="carousel" src="https://user-images.githubusercontent.com/1289805/78585111-2848c180-77ee-11ea-83e3-efb16e7968b0.png">

**Comment by zhawkins** [comment]
This was "a feature" but I think it's more trouble than it's worth. I've changed it so that it doesn't try to composer install it automatically and prompts you to do your own install.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/2671663/78821831-1874dd00-79a8-11ea-94c1-e1e9ebe4af38.png">


https://github.com/mediacurrent/theme_generator_8/pull/60
